# Generated by Django 5.2.1 on 2025-07-04 04:22

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
