# Generated by Django 5.2.1 on 2025-07-04 06:36

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
    ]
