databases:
  - name: clubfeeddb
    plan: free
    databaseName: clubfeed
    user: clubfeed

services:
  - type: web
    plan: free
    name: clubfeed
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn clubfeed.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clubfeed
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
