# Generated by Django 5.2.1 on 2025-05-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_club_slug_alter_club_name_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
