# Generated by Django 5.2.1 on 2025-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_club_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, default='a', unique=True),
            preserve_default=False,
        ),
    ]
