# Generated by Django 5.2.1 on 2025-05-29 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted',
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 4, 13, 43, 144053, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
