# Generated by Django 5.2.1 on 2025-06-17 02:36

import martor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_club_followers_alter_club_posters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
