# Generated by Django 5.2.1 on 2025-07-04 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_alter_club_description_alter_club_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='always_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='always_shown_for_groups',
            field=models.ManyToManyField(blank=True, related_name='always_shown_for_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='club',
            name='always_shown_for_users',
            field=models.ManyToManyField(blank=True, related_name='always_shown_for_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
