# Generated by Django 5.2.1 on 2025-07-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubimage',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='File name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubimage',
            name='show_on_club_page',
            field=models.BooleanField(default=False),
        ),
    ]
