# Generated by Django 5.2.1 on 2025-07-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_clubimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubimage',
            name='alt',
            field=models.CharField(blank=True, help_text='Describe the image for screen reader users and if the image cannot load.', max_length=255, verbose_name='Alternative description'),
        ),
    ]
