name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env File
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_DEBUG: 'False'
        envkey_SECRET_KEY: 'very-very-very-very-very-very-very-very-very-very-very-very-very-very-secret-secret-key'
        envkey_ALLOWED_HOSTS: ''
    - name: Run Tests
      run: |
        python manage.py test
